### ISSUE TITLE
Documentation: How to build from source?

### ISSUE THREAD

**Issue by hgoebl** [basarat/csx#2]
Would be nice to have a line in readme explaining how to build this project.
Or maybe a npm script entry...

**Comment by basarat** [comment]
done :rose:

**Comment by hgoebl** [comment]
Thanks, you're fast!

Without `-jsx react` it complains:

> Cannot use JSX unless the '--jsx' flag is provided.

**Comment by basarat** [comment]
> Without -jsx react it complains:

Thanks :rose: Fixed. Was missing that option in tsconfig.json
